# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wnormcor <wnormcor@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/16 08:02:03 by wnormcor          #+#    #+#              #
#    Updated: 2020/11/16 08:02:19 by wnormcor         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps-https
    protocol: TCP
    targetPort: 21
  - port: 10100
    name: ftps-passv
    protocol: TCP
    targetPort: 10100
  - port: 20
    name: ftps-data
    protocol: TCP
    targetPort: 20

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps-https
        - containerPort: 10100
          name: ftps-passv
        - containerPort: 20
          name: ftps-data
